title: The Dolpheverse Lore
description: Lore for Dolphe's Geometry Dash level series
markdown: kramdown
url: "https://dolphegd.github.io"
lang: en
image: /assets/images/image1.png
twitter_card: summary_large_image

links:
  team_discord: https://discord.gg/vm8P6xWHdv
  lore_discord: https://discord.gg/C9tkEYGcMQ
  google_doc: https://docs.google.com/document/d/1SG9VJY71UT77JTrUE-HR5_dAAgGHBUzb3nKtlRjXZe8/edit?usp=sharing
  timeline_slides: https://docs.google.com/presentation/d/1O-p_AB1jbQi3y7Q-Axrke7MKcVPh7OYxu0zh5VDWyII/edit?usp=sharing
  youtube: https://www.youtube.com/@dolphe

collections:
  classified:
    output: true
    permalink: /classified-files/:path/
  chronicles:
    output: true
    permalink: /chronicles/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: classified
    values:
      layout: entry
  - scope:
      path: ""
      type: chronicles
    values:
      layout: entry
